import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
const Navbar = () => {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsxs(motion.nav, { initial: { y: -50, opacity: 0 }, animate: { y: 0, opacity: 1 }, transition: { duration: 0.6 }, className: "w-full text-text p-4 fixed top-0 z-50 py-4 shadow-md bg-background-secondary", children: [_jsxs("div", { className: "mx-auto flex justify-between items-center relative z-50", children: [_jsx(Link, { to: "/", className: "text-text font-bold text-xl", children: "Career Companion" }), _jsxs("div", { className: "hidden md:flex space-x-4", children: [_jsx(Link, { to: "/explore", className: "text-text", children: "Explore Careers" }), _jsx(Link, { to: "/resources", className: "text-text", children: "Resources" }), _jsx(Link, { to: "/about", className: "text-text", children: "About Us" }), _jsx(Link, { to: "/login", className: "text-text", children: "Login" }), _jsx(Link, { to: "/register", className: "text-text", children: "Register" })] }), _jsx("div", { className: "md:hidden", children: _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "text-text focus:outline-none", children: _jsx("svg", { className: "h-6 w-6 fill-current", viewBox: "0 0 24 24", children: isOpen ? (_jsx("path", { fillRule: "evenodd", clipRule: "evenodd", d: "M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.829-4.828 4.829a1 1 0 0 1-1.414-1.414l4.829-4.828-4.829-4.828a1 1 0 1 1 1.414-1.414l4.828 4.829 4.829-4.829a1 1 0 1 1 1.414 1.414l-4.828 4.828 4.829 4.828z" })) : (_jsx("path", { fillRule: "evenodd", d: "M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2z" })) }) }) })] }), isOpen && (_jsxs("div", { className: "md:hidden mt-2", children: [_jsx(Link, { to: "/explore", className: "block text-text py-2", children: "Explore Careers" }), _jsx(Link, { to: "/resources", className: "block text-text py-2", children: "Resources" }), _jsx(Link, { to: "/community", className: "block text-text py-2", children: "Community" }), _jsx(Link, { to: "/profile", className: "block text-text py-2", children: "Profile" }), _jsx(Link, { to: "/login", className: "block text-text py-2", children: "Login" }), _jsx(Link, { to: "/register", className: "block text-text py-2", children: "Register" })] }))] }));
};
export default Navbar;
